#DEBUG = 1 
INCDIR = $(TDLPATH)\h
LIBDIR = $(TDLPATH)\lib

!ifdef DEBUG

CFLAGS = -4r -hw -db -d2 -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zp4 -zdp -zl -xs
AFLAGS = -f obj
LFLAGS = system DarkX

!else

CFLAGS = -4r -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zdp -zl -d2 -xs
AFLAGS = -f obj
LFLAGS = system DarkX

!endif

.asm.obj:
        tasm $(AFLAGS) $?
.c.obj:
        wcc386 $(CFLAGS) $?
.cpp.obj:
        wpp386 $(CFLAGS) $?

# 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴

all: tubes.exe

tubes.obj: tubes.cpp $(INCDIR)\tdl.h

tubes.exe: tubes.obj $(LIBDIR)\tdl.lib
        wlink $(LFLAGS) file $(LIBDIR)\c0tt, $(LIBDIR)\wpp, tubes library $(LIBDIR)\tdl.lib name tubes

